spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/user_service
    username: ttsk
    password: ttsk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8110